server:
  port: ":8040"
  public: "http://localhost:8040"
db:
  user: root
  password: 1
  host: 127.0.0.1
  database: users
  path: "./db.sqlite"
features:
  withreactions: true
  withfiles: true
  withgroupcalls: true
  withvoicemessages: true
livekit:
  enabled: true
  host: "https://livekit.webix.io"
  apikey: demo
  apisecret: ol9385c0c9h237850h283549h2305823